name: Gather Wikipedia category tree and upload to GH Pages

on:
    schedule:
      - cron: '30 5 * * *'
    workflow_dispatch:

permissions:
    id-token: write
    pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pages_generated: ${{steps.upload_artifact.outputs.artifact_uploaded}}
    steps:
        - uses: actions/checkout@v4
        
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12' 
        
        - name: Install requirements
          run: python3 -m pip install -r ./requirements.txt
        
        - run: GH_PAGES_URL="https://jon-edward.github.io/wiki-categories/" sh ./build.sh
        
        - name: Upload artifact
          id: upload_artifact
          if: ${{ hashFiles('pages/run_info.json') != '' }}
          uses: actions/upload-pages-artifact@v2
          with:
            path: 'pages'
          run: echo "artifact_uploaded=true" >> "$GITHUB_OUTPUT"
    
  deploy:
    needs: build
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
        - name: Deploy to GitHub Pages
          if: ${{needs.build.outputs.pages_generated}}
          id: deployment
          uses: actions/deploy-pages@v3
