name: Gather Wikipedia category tree and upload to GH Pages

on:
    schedule:
      - cron: '30 5 * * *'
    workflow_dispatch:
      inputs:
        force:
          type: boolean
          description: Force run execution, not checking for redundancy

permissions:
    id-token: write
    pages: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12' 
        
        - name: Install requirements
          run: python3 -m pip install -r ./requirements.txt
        
        - name: Build category tree
          run: |
            export GH_PAGES_URL="https://jon-edward.github.io/wiki-categories/"
            
            if [[ ${{ inputs.force == true }} == true ]]; then
              unset GH_PAGES_URL
            fi
            
            python3 ./categories en \
              --excluded-parents 15961454 869270 \
              --excluded-article-categories 43077354
            
            touch ./pages/.nojekyll
        
        - name: Upload artifact
          if: ${{ hashFiles('pages/run_info.json') != '' }}
          uses: actions/upload-pages-artifact@v2
          with:
            path: 'pages'

        - name: Deploy to GitHub Pages
          if: ${{ hashFiles('pages/run_info.json') != '' }}
          id: deployment
          uses: actions/deploy-pages@v3
